// Generated by gencpp from file tester/WordCount.msg
// DO NOT EDIT!


#ifndef TESTER_MESSAGE_WORDCOUNT_H
#define TESTER_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <tester/WordCountRequest.h>
#include <tester/WordCountResponse.h>


namespace tester
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace tester


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tester::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::tester::WordCount&) { return value(); }
};

template<>
struct DataType< ::tester::WordCount > {
  static const char* value()
  {
    return "tester/WordCount";
  }

  static const char* value(const ::tester::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::tester::WordCountRequest> should match 
// service_traits::MD5Sum< ::tester::WordCount > 
template<>
struct MD5Sum< ::tester::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tester::WordCount >::value();
  }
  static const char* value(const ::tester::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tester::WordCountRequest> should match 
// service_traits::DataType< ::tester::WordCount > 
template<>
struct DataType< ::tester::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::tester::WordCount >::value();
  }
  static const char* value(const ::tester::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tester::WordCountResponse> should match 
// service_traits::MD5Sum< ::tester::WordCount > 
template<>
struct MD5Sum< ::tester::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tester::WordCount >::value();
  }
  static const char* value(const ::tester::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tester::WordCountResponse> should match 
// service_traits::DataType< ::tester::WordCount > 
template<>
struct DataType< ::tester::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::tester::WordCount >::value();
  }
  static const char* value(const ::tester::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTER_MESSAGE_WORDCOUNT_H
